// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/terraform-provider-iris/models"
)

// NewCreateDHCPSubnetParams creates a new CreateDHCPSubnetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDHCPSubnetParams() *CreateDHCPSubnetParams {
	return &CreateDHCPSubnetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDHCPSubnetParamsWithTimeout creates a new CreateDHCPSubnetParams object
// with the ability to set a timeout on a request.
func NewCreateDHCPSubnetParamsWithTimeout(timeout time.Duration) *CreateDHCPSubnetParams {
	return &CreateDHCPSubnetParams{
		timeout: timeout,
	}
}

// NewCreateDHCPSubnetParamsWithContext creates a new CreateDHCPSubnetParams object
// with the ability to set a context for a request.
func NewCreateDHCPSubnetParamsWithContext(ctx context.Context) *CreateDHCPSubnetParams {
	return &CreateDHCPSubnetParams{
		Context: ctx,
	}
}

// NewCreateDHCPSubnetParamsWithHTTPClient creates a new CreateDHCPSubnetParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDHCPSubnetParamsWithHTTPClient(client *http.Client) *CreateDHCPSubnetParams {
	return &CreateDHCPSubnetParams{
		HTTPClient: client,
	}
}

/*
CreateDHCPSubnetParams contains all the parameters to send to the API endpoint

	for the create d h c p subnet operation.

	Typically these are written to a http.Request.
*/
type CreateDHCPSubnetParams struct {

	// Body.
	Body *models.Subnet

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDHCPSubnetParams) WithDefaults() *CreateDHCPSubnetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDHCPSubnetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) WithTimeout(timeout time.Duration) *CreateDHCPSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) WithContext(ctx context.Context) *CreateDHCPSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) WithHTTPClient(client *http.Client) *CreateDHCPSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) WithBody(body *models.Subnet) *CreateDHCPSubnetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create d h c p subnet params
func (o *CreateDHCPSubnetParams) SetBody(body *models.Subnet) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDHCPSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
