// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/terraform-provider-iris/models"
)

// NewCreateDHCPSubnetReservationParams creates a new CreateDHCPSubnetReservationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDHCPSubnetReservationParams() *CreateDHCPSubnetReservationParams {
	return &CreateDHCPSubnetReservationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDHCPSubnetReservationParamsWithTimeout creates a new CreateDHCPSubnetReservationParams object
// with the ability to set a timeout on a request.
func NewCreateDHCPSubnetReservationParamsWithTimeout(timeout time.Duration) *CreateDHCPSubnetReservationParams {
	return &CreateDHCPSubnetReservationParams{
		timeout: timeout,
	}
}

// NewCreateDHCPSubnetReservationParamsWithContext creates a new CreateDHCPSubnetReservationParams object
// with the ability to set a context for a request.
func NewCreateDHCPSubnetReservationParamsWithContext(ctx context.Context) *CreateDHCPSubnetReservationParams {
	return &CreateDHCPSubnetReservationParams{
		Context: ctx,
	}
}

// NewCreateDHCPSubnetReservationParamsWithHTTPClient creates a new CreateDHCPSubnetReservationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDHCPSubnetReservationParamsWithHTTPClient(client *http.Client) *CreateDHCPSubnetReservationParams {
	return &CreateDHCPSubnetReservationParams{
		HTTPClient: client,
	}
}

/*
CreateDHCPSubnetReservationParams contains all the parameters to send to the API endpoint

	for the create d h c p subnet reservation operation.

	Typically these are written to a http.Request.
*/
type CreateDHCPSubnetReservationParams struct {

	// Body.
	Body *models.Reservation

	/* SubnetID.

	   The ID of the DHCP subnet to create reservations on.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDHCPSubnetReservationParams) WithDefaults() *CreateDHCPSubnetReservationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDHCPSubnetReservationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) WithTimeout(timeout time.Duration) *CreateDHCPSubnetReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) WithContext(ctx context.Context) *CreateDHCPSubnetReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) WithHTTPClient(client *http.Client) *CreateDHCPSubnetReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) WithBody(body *models.Reservation) *CreateDHCPSubnetReservationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) SetBody(body *models.Reservation) {
	o.Body = body
}

// WithSubnetID adds the subnetID to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) WithSubnetID(subnetID string) *CreateDHCPSubnetReservationParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the create d h c p subnet reservation params
func (o *CreateDHCPSubnetReservationParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDHCPSubnetReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
