// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDHCPSubnetParams creates a new DeleteDHCPSubnetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDHCPSubnetParams() *DeleteDHCPSubnetParams {
	return &DeleteDHCPSubnetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDHCPSubnetParamsWithTimeout creates a new DeleteDHCPSubnetParams object
// with the ability to set a timeout on a request.
func NewDeleteDHCPSubnetParamsWithTimeout(timeout time.Duration) *DeleteDHCPSubnetParams {
	return &DeleteDHCPSubnetParams{
		timeout: timeout,
	}
}

// NewDeleteDHCPSubnetParamsWithContext creates a new DeleteDHCPSubnetParams object
// with the ability to set a context for a request.
func NewDeleteDHCPSubnetParamsWithContext(ctx context.Context) *DeleteDHCPSubnetParams {
	return &DeleteDHCPSubnetParams{
		Context: ctx,
	}
}

// NewDeleteDHCPSubnetParamsWithHTTPClient creates a new DeleteDHCPSubnetParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDHCPSubnetParamsWithHTTPClient(client *http.Client) *DeleteDHCPSubnetParams {
	return &DeleteDHCPSubnetParams{
		HTTPClient: client,
	}
}

/*
DeleteDHCPSubnetParams contains all the parameters to send to the API endpoint

	for the delete d h c p subnet operation.

	Typically these are written to a http.Request.
*/
type DeleteDHCPSubnetParams struct {

	/* SubnetID.

	   The ID of the subnet to delete.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDHCPSubnetParams) WithDefaults() *DeleteDHCPSubnetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDHCPSubnetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) WithTimeout(timeout time.Duration) *DeleteDHCPSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) WithContext(ctx context.Context) *DeleteDHCPSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) WithHTTPClient(client *http.Client) *DeleteDHCPSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubnetID adds the subnetID to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) WithSubnetID(subnetID string) *DeleteDHCPSubnetParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the delete d h c p subnet params
func (o *DeleteDHCPSubnetParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDHCPSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
