// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDisableDHCPParams creates a new DisableDHCPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDisableDHCPParams() *DisableDHCPParams {
	return &DisableDHCPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDisableDHCPParamsWithTimeout creates a new DisableDHCPParams object
// with the ability to set a timeout on a request.
func NewDisableDHCPParamsWithTimeout(timeout time.Duration) *DisableDHCPParams {
	return &DisableDHCPParams{
		timeout: timeout,
	}
}

// NewDisableDHCPParamsWithContext creates a new DisableDHCPParams object
// with the ability to set a context for a request.
func NewDisableDHCPParamsWithContext(ctx context.Context) *DisableDHCPParams {
	return &DisableDHCPParams{
		Context: ctx,
	}
}

// NewDisableDHCPParamsWithHTTPClient creates a new DisableDHCPParams object
// with the ability to set a custom HTTPClient for a request.
func NewDisableDHCPParamsWithHTTPClient(client *http.Client) *DisableDHCPParams {
	return &DisableDHCPParams{
		HTTPClient: client,
	}
}

/*
DisableDHCPParams contains all the parameters to send to the API endpoint

	for the disable d h c p operation.

	Typically these are written to a http.Request.
*/
type DisableDHCPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the disable d h c p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableDHCPParams) WithDefaults() *DisableDHCPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the disable d h c p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableDHCPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the disable d h c p params
func (o *DisableDHCPParams) WithTimeout(timeout time.Duration) *DisableDHCPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable d h c p params
func (o *DisableDHCPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable d h c p params
func (o *DisableDHCPParams) WithContext(ctx context.Context) *DisableDHCPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable d h c p params
func (o *DisableDHCPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable d h c p params
func (o *DisableDHCPParams) WithHTTPClient(client *http.Client) *DisableDHCPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable d h c p params
func (o *DisableDHCPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DisableDHCPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
