// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEnableDHCPParams creates a new EnableDHCPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnableDHCPParams() *EnableDHCPParams {
	return &EnableDHCPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEnableDHCPParamsWithTimeout creates a new EnableDHCPParams object
// with the ability to set a timeout on a request.
func NewEnableDHCPParamsWithTimeout(timeout time.Duration) *EnableDHCPParams {
	return &EnableDHCPParams{
		timeout: timeout,
	}
}

// NewEnableDHCPParamsWithContext creates a new EnableDHCPParams object
// with the ability to set a context for a request.
func NewEnableDHCPParamsWithContext(ctx context.Context) *EnableDHCPParams {
	return &EnableDHCPParams{
		Context: ctx,
	}
}

// NewEnableDHCPParamsWithHTTPClient creates a new EnableDHCPParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnableDHCPParamsWithHTTPClient(client *http.Client) *EnableDHCPParams {
	return &EnableDHCPParams{
		HTTPClient: client,
	}
}

/*
EnableDHCPParams contains all the parameters to send to the API endpoint

	for the enable d h c p operation.

	Typically these are written to a http.Request.
*/
type EnableDHCPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the enable d h c p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnableDHCPParams) WithDefaults() *EnableDHCPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the enable d h c p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnableDHCPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the enable d h c p params
func (o *EnableDHCPParams) WithTimeout(timeout time.Duration) *EnableDHCPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable d h c p params
func (o *EnableDHCPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable d h c p params
func (o *EnableDHCPParams) WithContext(ctx context.Context) *EnableDHCPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable d h c p params
func (o *EnableDHCPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable d h c p params
func (o *EnableDHCPParams) WithHTTPClient(client *http.Client) *EnableDHCPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable d h c p params
func (o *EnableDHCPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EnableDHCPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
