// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllDHCPSubnetsParams creates a new GetAllDHCPSubnetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllDHCPSubnetsParams() *GetAllDHCPSubnetsParams {
	return &GetAllDHCPSubnetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllDHCPSubnetsParamsWithTimeout creates a new GetAllDHCPSubnetsParams object
// with the ability to set a timeout on a request.
func NewGetAllDHCPSubnetsParamsWithTimeout(timeout time.Duration) *GetAllDHCPSubnetsParams {
	return &GetAllDHCPSubnetsParams{
		timeout: timeout,
	}
}

// NewGetAllDHCPSubnetsParamsWithContext creates a new GetAllDHCPSubnetsParams object
// with the ability to set a context for a request.
func NewGetAllDHCPSubnetsParamsWithContext(ctx context.Context) *GetAllDHCPSubnetsParams {
	return &GetAllDHCPSubnetsParams{
		Context: ctx,
	}
}

// NewGetAllDHCPSubnetsParamsWithHTTPClient creates a new GetAllDHCPSubnetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllDHCPSubnetsParamsWithHTTPClient(client *http.Client) *GetAllDHCPSubnetsParams {
	return &GetAllDHCPSubnetsParams{
		HTTPClient: client,
	}
}

/*
GetAllDHCPSubnetsParams contains all the parameters to send to the API endpoint

	for the get all d h c p subnets operation.

	Typically these are written to a http.Request.
*/
type GetAllDHCPSubnetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all d h c p subnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDHCPSubnetsParams) WithDefaults() *GetAllDHCPSubnetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all d h c p subnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDHCPSubnetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) WithTimeout(timeout time.Duration) *GetAllDHCPSubnetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) WithContext(ctx context.Context) *GetAllDHCPSubnetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) WithHTTPClient(client *http.Client) *GetAllDHCPSubnetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all d h c p subnets params
func (o *GetAllDHCPSubnetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllDHCPSubnetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
