// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDHCPSubnetParams creates a new GetDHCPSubnetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDHCPSubnetParams() *GetDHCPSubnetParams {
	return &GetDHCPSubnetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDHCPSubnetParamsWithTimeout creates a new GetDHCPSubnetParams object
// with the ability to set a timeout on a request.
func NewGetDHCPSubnetParamsWithTimeout(timeout time.Duration) *GetDHCPSubnetParams {
	return &GetDHCPSubnetParams{
		timeout: timeout,
	}
}

// NewGetDHCPSubnetParamsWithContext creates a new GetDHCPSubnetParams object
// with the ability to set a context for a request.
func NewGetDHCPSubnetParamsWithContext(ctx context.Context) *GetDHCPSubnetParams {
	return &GetDHCPSubnetParams{
		Context: ctx,
	}
}

// NewGetDHCPSubnetParamsWithHTTPClient creates a new GetDHCPSubnetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDHCPSubnetParamsWithHTTPClient(client *http.Client) *GetDHCPSubnetParams {
	return &GetDHCPSubnetParams{
		HTTPClient: client,
	}
}

/*
GetDHCPSubnetParams contains all the parameters to send to the API endpoint

	for the get d h c p subnet operation.

	Typically these are written to a http.Request.
*/
type GetDHCPSubnetParams struct {

	/* SubnetID.

	   The ID of the DHCP subnet to query.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDHCPSubnetParams) WithDefaults() *GetDHCPSubnetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get d h c p subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDHCPSubnetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get d h c p subnet params
func (o *GetDHCPSubnetParams) WithTimeout(timeout time.Duration) *GetDHCPSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get d h c p subnet params
func (o *GetDHCPSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get d h c p subnet params
func (o *GetDHCPSubnetParams) WithContext(ctx context.Context) *GetDHCPSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get d h c p subnet params
func (o *GetDHCPSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get d h c p subnet params
func (o *GetDHCPSubnetParams) WithHTTPClient(client *http.Client) *GetDHCPSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get d h c p subnet params
func (o *GetDHCPSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubnetID adds the subnetID to the get d h c p subnet params
func (o *GetDHCPSubnetParams) WithSubnetID(subnetID string) *GetDHCPSubnetParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the get d h c p subnet params
func (o *GetDHCPSubnetParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDHCPSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
