// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/terraform-provider-iris/models"
)

// GetDHCPSubnetReader is a Reader for the GetDHCPSubnet structure.
type GetDHCPSubnetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDHCPSubnetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDHCPSubnetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDHCPSubnetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDHCPSubnetOK creates a GetDHCPSubnetOK with default headers values
func NewGetDHCPSubnetOK() *GetDHCPSubnetOK {
	return &GetDHCPSubnetOK{}
}

/*
GetDHCPSubnetOK describes a response with status code 200, with default header values.

Returns the DHCP Subnet object.
*/
type GetDHCPSubnetOK struct {
	Payload *models.Subnet
}

// IsSuccess returns true when this get d h c p subnet o k response has a 2xx status code
func (o *GetDHCPSubnetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get d h c p subnet o k response has a 3xx status code
func (o *GetDHCPSubnetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get d h c p subnet o k response has a 4xx status code
func (o *GetDHCPSubnetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get d h c p subnet o k response has a 5xx status code
func (o *GetDHCPSubnetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get d h c p subnet o k response a status code equal to that given
func (o *GetDHCPSubnetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get d h c p subnet o k response
func (o *GetDHCPSubnetOK) Code() int {
	return 200
}

func (o *GetDHCPSubnetOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/subnet/{subnetId}][%d] getDHCPSubnetOK  %+v", 200, o.Payload)
}

func (o *GetDHCPSubnetOK) String() string {
	return fmt.Sprintf("[GET /dhcp/subnet/{subnetId}][%d] getDHCPSubnetOK  %+v", 200, o.Payload)
}

func (o *GetDHCPSubnetOK) GetPayload() *models.Subnet {
	return o.Payload
}

func (o *GetDHCPSubnetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Subnet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDHCPSubnetNotFound creates a GetDHCPSubnetNotFound with default headers values
func NewGetDHCPSubnetNotFound() *GetDHCPSubnetNotFound {
	return &GetDHCPSubnetNotFound{}
}

/*
GetDHCPSubnetNotFound describes a response with status code 404, with default header values.

Invalid subnet ID was provided.
*/
type GetDHCPSubnetNotFound struct {
}

// IsSuccess returns true when this get d h c p subnet not found response has a 2xx status code
func (o *GetDHCPSubnetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get d h c p subnet not found response has a 3xx status code
func (o *GetDHCPSubnetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get d h c p subnet not found response has a 4xx status code
func (o *GetDHCPSubnetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get d h c p subnet not found response has a 5xx status code
func (o *GetDHCPSubnetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get d h c p subnet not found response a status code equal to that given
func (o *GetDHCPSubnetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get d h c p subnet not found response
func (o *GetDHCPSubnetNotFound) Code() int {
	return 404
}

func (o *GetDHCPSubnetNotFound) Error() string {
	return fmt.Sprintf("[GET /dhcp/subnet/{subnetId}][%d] getDHCPSubnetNotFound ", 404)
}

func (o *GetDHCPSubnetNotFound) String() string {
	return fmt.Sprintf("[GET /dhcp/subnet/{subnetId}][%d] getDHCPSubnetNotFound ", 404)
}

func (o *GetDHCPSubnetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
