// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDHCPSubnetReservationParams creates a new GetDHCPSubnetReservationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDHCPSubnetReservationParams() *GetDHCPSubnetReservationParams {
	return &GetDHCPSubnetReservationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDHCPSubnetReservationParamsWithTimeout creates a new GetDHCPSubnetReservationParams object
// with the ability to set a timeout on a request.
func NewGetDHCPSubnetReservationParamsWithTimeout(timeout time.Duration) *GetDHCPSubnetReservationParams {
	return &GetDHCPSubnetReservationParams{
		timeout: timeout,
	}
}

// NewGetDHCPSubnetReservationParamsWithContext creates a new GetDHCPSubnetReservationParams object
// with the ability to set a context for a request.
func NewGetDHCPSubnetReservationParamsWithContext(ctx context.Context) *GetDHCPSubnetReservationParams {
	return &GetDHCPSubnetReservationParams{
		Context: ctx,
	}
}

// NewGetDHCPSubnetReservationParamsWithHTTPClient creates a new GetDHCPSubnetReservationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDHCPSubnetReservationParamsWithHTTPClient(client *http.Client) *GetDHCPSubnetReservationParams {
	return &GetDHCPSubnetReservationParams{
		HTTPClient: client,
	}
}

/*
GetDHCPSubnetReservationParams contains all the parameters to send to the API endpoint

	for the get d h c p subnet reservation operation.

	Typically these are written to a http.Request.
*/
type GetDHCPSubnetReservationParams struct {

	/* MacID.

	   The hardware MAC address of the reservation to query.
	*/
	MacID string

	/* SubnetID.

	   The ID of the DHCP subnet to query.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDHCPSubnetReservationParams) WithDefaults() *GetDHCPSubnetReservationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDHCPSubnetReservationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) WithTimeout(timeout time.Duration) *GetDHCPSubnetReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) WithContext(ctx context.Context) *GetDHCPSubnetReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) WithHTTPClient(client *http.Client) *GetDHCPSubnetReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMacID adds the macID to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) WithMacID(macID string) *GetDHCPSubnetReservationParams {
	o.SetMacID(macID)
	return o
}

// SetMacID adds the macId to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) SetMacID(macID string) {
	o.MacID = macID
}

// WithSubnetID adds the subnetID to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) WithSubnetID(subnetID string) *GetDHCPSubnetReservationParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the get d h c p subnet reservation params
func (o *GetDHCPSubnetReservationParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDHCPSubnetReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param macID
	if err := r.SetPathParam("macID", o.MacID); err != nil {
		return err
	}

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
