// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllDHCPSubnetReservationsParams creates a new GetAllDHCPSubnetReservationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllDHCPSubnetReservationsParams() *GetAllDHCPSubnetReservationsParams {
	return &GetAllDHCPSubnetReservationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllDHCPSubnetReservationsParamsWithTimeout creates a new GetAllDHCPSubnetReservationsParams object
// with the ability to set a timeout on a request.
func NewGetAllDHCPSubnetReservationsParamsWithTimeout(timeout time.Duration) *GetAllDHCPSubnetReservationsParams {
	return &GetAllDHCPSubnetReservationsParams{
		timeout: timeout,
	}
}

// NewGetAllDHCPSubnetReservationsParamsWithContext creates a new GetAllDHCPSubnetReservationsParams object
// with the ability to set a context for a request.
func NewGetAllDHCPSubnetReservationsParamsWithContext(ctx context.Context) *GetAllDHCPSubnetReservationsParams {
	return &GetAllDHCPSubnetReservationsParams{
		Context: ctx,
	}
}

// NewGetAllDHCPSubnetReservationsParamsWithHTTPClient creates a new GetAllDHCPSubnetReservationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllDHCPSubnetReservationsParamsWithHTTPClient(client *http.Client) *GetAllDHCPSubnetReservationsParams {
	return &GetAllDHCPSubnetReservationsParams{
		HTTPClient: client,
	}
}

/*
GetAllDHCPSubnetReservationsParams contains all the parameters to send to the API endpoint

	for the get all d h c p subnet reservations operation.

	Typically these are written to a http.Request.
*/
type GetAllDHCPSubnetReservationsParams struct {

	/* SubnetID.

	   The ID of the DHCP subnet to get reservations from.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all d h c p subnet reservations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDHCPSubnetReservationsParams) WithDefaults() *GetAllDHCPSubnetReservationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all d h c p subnet reservations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDHCPSubnetReservationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) WithTimeout(timeout time.Duration) *GetAllDHCPSubnetReservationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) WithContext(ctx context.Context) *GetAllDHCPSubnetReservationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) WithHTTPClient(client *http.Client) *GetAllDHCPSubnetReservationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubnetID adds the subnetID to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) WithSubnetID(subnetID string) *GetAllDHCPSubnetReservationsParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the get all d h c p subnet reservations params
func (o *GetAllDHCPSubnetReservationsParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllDHCPSubnetReservationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
