// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReloadDHCPReader is a Reader for the ReloadDHCP structure.
type ReloadDHCPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReloadDHCPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewReloadDHCPCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewReloadDHCPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReloadDHCPCreated creates a ReloadDHCPCreated with default headers values
func NewReloadDHCPCreated() *ReloadDHCPCreated {
	return &ReloadDHCPCreated{}
}

/*
ReloadDHCPCreated describes a response with status code 201, with default header values.

The DHCPv4 service configuration has been reloaded.
*/
type ReloadDHCPCreated struct {
}

// IsSuccess returns true when this reload d h c p created response has a 2xx status code
func (o *ReloadDHCPCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reload d h c p created response has a 3xx status code
func (o *ReloadDHCPCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reload d h c p created response has a 4xx status code
func (o *ReloadDHCPCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this reload d h c p created response has a 5xx status code
func (o *ReloadDHCPCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this reload d h c p created response a status code equal to that given
func (o *ReloadDHCPCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the reload d h c p created response
func (o *ReloadDHCPCreated) Code() int {
	return 201
}

func (o *ReloadDHCPCreated) Error() string {
	return fmt.Sprintf("[POST /dhcp/reload][%d] reloadDHCPCreated ", 201)
}

func (o *ReloadDHCPCreated) String() string {
	return fmt.Sprintf("[POST /dhcp/reload][%d] reloadDHCPCreated ", 201)
}

func (o *ReloadDHCPCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReloadDHCPInternalServerError creates a ReloadDHCPInternalServerError with default headers values
func NewReloadDHCPInternalServerError() *ReloadDHCPInternalServerError {
	return &ReloadDHCPInternalServerError{}
}

/*
ReloadDHCPInternalServerError describes a response with status code 500, with default header values.

Unable to reload the DHCPv4 service configuration.
*/
type ReloadDHCPInternalServerError struct {
}

// IsSuccess returns true when this reload d h c p internal server error response has a 2xx status code
func (o *ReloadDHCPInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reload d h c p internal server error response has a 3xx status code
func (o *ReloadDHCPInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reload d h c p internal server error response has a 4xx status code
func (o *ReloadDHCPInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this reload d h c p internal server error response has a 5xx status code
func (o *ReloadDHCPInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this reload d h c p internal server error response a status code equal to that given
func (o *ReloadDHCPInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the reload d h c p internal server error response
func (o *ReloadDHCPInternalServerError) Code() int {
	return 500
}

func (o *ReloadDHCPInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dhcp/reload][%d] reloadDHCPInternalServerError ", 500)
}

func (o *ReloadDHCPInternalServerError) String() string {
	return fmt.Sprintf("[POST /dhcp/reload][%d] reloadDHCPInternalServerError ", 500)
}

func (o *ReloadDHCPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
