// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/terraform-provider-iris/models"
)

// NewUpdateDHCPSubnetReservationParams creates a new UpdateDHCPSubnetReservationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDHCPSubnetReservationParams() *UpdateDHCPSubnetReservationParams {
	return &UpdateDHCPSubnetReservationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDHCPSubnetReservationParamsWithTimeout creates a new UpdateDHCPSubnetReservationParams object
// with the ability to set a timeout on a request.
func NewUpdateDHCPSubnetReservationParamsWithTimeout(timeout time.Duration) *UpdateDHCPSubnetReservationParams {
	return &UpdateDHCPSubnetReservationParams{
		timeout: timeout,
	}
}

// NewUpdateDHCPSubnetReservationParamsWithContext creates a new UpdateDHCPSubnetReservationParams object
// with the ability to set a context for a request.
func NewUpdateDHCPSubnetReservationParamsWithContext(ctx context.Context) *UpdateDHCPSubnetReservationParams {
	return &UpdateDHCPSubnetReservationParams{
		Context: ctx,
	}
}

// NewUpdateDHCPSubnetReservationParamsWithHTTPClient creates a new UpdateDHCPSubnetReservationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDHCPSubnetReservationParamsWithHTTPClient(client *http.Client) *UpdateDHCPSubnetReservationParams {
	return &UpdateDHCPSubnetReservationParams{
		HTTPClient: client,
	}
}

/*
UpdateDHCPSubnetReservationParams contains all the parameters to send to the API endpoint

	for the update d h c p subnet reservation operation.

	Typically these are written to a http.Request.
*/
type UpdateDHCPSubnetReservationParams struct {

	// Body.
	Body *models.Reservation

	/* MacID.

	   The hardware MAC address of the reservation to update.
	*/
	MacID string

	/* SubnetID.

	   The ID of the subnet's reservation to update.
	*/
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDHCPSubnetReservationParams) WithDefaults() *UpdateDHCPSubnetReservationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update d h c p subnet reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDHCPSubnetReservationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithTimeout(timeout time.Duration) *UpdateDHCPSubnetReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithContext(ctx context.Context) *UpdateDHCPSubnetReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithHTTPClient(client *http.Client) *UpdateDHCPSubnetReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithBody(body *models.Reservation) *UpdateDHCPSubnetReservationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetBody(body *models.Reservation) {
	o.Body = body
}

// WithMacID adds the macID to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithMacID(macID string) *UpdateDHCPSubnetReservationParams {
	o.SetMacID(macID)
	return o
}

// SetMacID adds the macId to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetMacID(macID string) {
	o.MacID = macID
}

// WithSubnetID adds the subnetID to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) WithSubnetID(subnetID string) *UpdateDHCPSubnetReservationParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the update d h c p subnet reservation params
func (o *UpdateDHCPSubnetReservationParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDHCPSubnetReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param macID
	if err := r.SetPathParam("macID", o.MacID); err != nil {
		return err
	}

	// path param subnetId
	if err := r.SetPathParam("subnetId", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
