// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SubnetPoolRange subnet pool range
// Example: {"first":"192.168.0.51","last":"192.168.0.99"}
//
// swagger:model SubnetPoolRange
type SubnetPoolRange struct {

	// The subnet's first IP address for DHCP dynamic leases.
	First string `json:"first,omitempty"`

	// The subnet's last IP address for DHCP dynamic leases.
	Last string `json:"last,omitempty"`
}

// Validate validates this subnet pool range
func (m *SubnetPoolRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this subnet pool range based on context it is used
func (m *SubnetPoolRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubnetPoolRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubnetPoolRange) UnmarshalBinary(b []byte) error {
	var res SubnetPoolRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
